# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_cercacat.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cercacat(object):
    def setupUi(self, cercacat):
        cercacat.setObjectName("cercacat")
        cercacat.resize(320, 946)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LOGO = QtWidgets.QLabel(self.dockWidgetContents)
        self.LOGO.setText("")
        self.LOGO.setPixmap(QtGui.QPixmap(":/plugins/Cxf_in/icon.png"))
        self.LOGO.setObjectName("LOGO")
        self.gridLayout_4.addWidget(self.LOGO, 0, 0, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.dockWidgetContents)
        self.toolBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolBox.setMouseTracking(True)
        self.toolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBox.setObjectName("toolBox")
        self.viewspatialite = QtWidgets.QWidget()
        self.viewspatialite.setGeometry(QtCore.QRect(0, 0, 302, 661))
        self.viewspatialite.setObjectName("viewspatialite")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.viewspatialite)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.viewall = QtWidgets.QPushButton(self.viewspatialite)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.viewall.setFont(font)
        self.viewall.setObjectName("viewall")
        self.gridLayout_2.addWidget(self.viewall, 0, 0, 1, 1)
        self.viewsel = QtWidgets.QPushButton(self.viewspatialite)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.viewsel.setFont(font)
        self.viewsel.setObjectName("viewsel")
        self.gridLayout_2.addWidget(self.viewsel, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.singolfg = QtWidgets.QCheckBox(self.viewspatialite)
        self.singolfg.setObjectName("singolfg")
        self.gridLayout_5.addWidget(self.singolfg, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.viewspatialite)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.viewspatialite)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 3)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.listcomune = QtWidgets.QTreeWidget(self.viewspatialite)
        self.listcomune.setObjectName("listcomune")
        self.listcomune.headerItem().setText(0, "1")
        self.listcomune.header().setVisible(False)
        self.gridLayout_6.addWidget(self.listcomune, 1, 0, 1, 1)
        self.toolBox.addItem(self.viewspatialite, "")
        self.ric_mapp = QtWidgets.QWidget()
        self.ric_mapp.setGeometry(QtCore.QRect(0, 0, 302, 661))
        self.ric_mapp.setObjectName("ric_mapp")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ric_mapp)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gruppocatsearch = QtWidgets.QGroupBox(self.ric_mapp)
        self.gruppocatsearch.setTitle("")
        self.gruppocatsearch.setObjectName("gruppocatsearch")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gruppocatsearch)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cat_mapp = QtWidgets.QComboBox(self.gruppocatsearch)
        self.cat_mapp.setEnabled(False)
        self.cat_mapp.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cat_mapp.setEditable(False)
        self.cat_mapp.setObjectName("cat_mapp")
        self.gridLayout_3.addWidget(self.cat_mapp, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gruppocatsearch)
        self.label_4.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setMouseTracking(False)
        self.label_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.cat_com = QtWidgets.QComboBox(self.gruppocatsearch)
        self.cat_com.setEnabled(True)
        self.cat_com.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cat_com.setEditable(False)
        self.cat_com.setObjectName("cat_com")
        self.gridLayout_3.addWidget(self.cat_com, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gruppocatsearch)
        self.label_5.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setMouseTracking(False)
        self.label_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gruppocatsearch)
        self.label.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.cat_fg = QtWidgets.QComboBox(self.gruppocatsearch)
        self.cat_fg.setEnabled(False)
        self.cat_fg.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cat_fg.setEditable(False)
        self.cat_fg.setMaxVisibleItems(2147483647)
        self.cat_fg.setObjectName("cat_fg")
        self.gridLayout_3.addWidget(self.cat_fg, 1, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.gruppocatsearch)
        self.toolBox.addItem(self.ric_mapp, "")
        self.cxf_load_memory = QtWidgets.QWidget()
        self.cxf_load_memory.setGeometry(QtCore.QRect(0, 0, 302, 661))
        self.cxf_load_memory.setObjectName("cxf_load_memory")
        self.cxfmemory = QtWidgets.QPushButton(self.cxf_load_memory)
        self.cxfmemory.setGeometry(QtCore.QRect(9, 9, 198, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cxfmemory.setFont(font)
        self.cxfmemory.setObjectName("cxfmemory")
        self.toolBox.addItem(self.cxf_load_memory, "")
        self.cxf_load_spatialite = QtWidgets.QWidget()
        self.cxf_load_spatialite.setGeometry(QtCore.QRect(0, 0, 302, 661))
        self.cxf_load_spatialite.setObjectName("cxf_load_spatialite")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.cxf_load_spatialite)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.georef_db = QtWidgets.QCheckBox(self.cxf_load_spatialite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.georef_db.sizePolicy().hasHeightForWidth())
        self.georef_db.setSizePolicy(sizePolicy)
        self.georef_db.setMaximumSize(QtCore.QSize(300, 20))
        self.georef_db.setObjectName("georef_db")
        self.horizontalLayout_5.addWidget(self.georef_db)
        self.Regionefvg = QtWidgets.QGroupBox(self.cxf_load_spatialite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Regionefvg.sizePolicy().hasHeightForWidth())
        self.Regionefvg.setSizePolicy(sizePolicy)
        self.Regionefvg.setMinimumSize(QtCore.QSize(0, 40))
        self.Regionefvg.setMaximumSize(QtCore.QSize(140, 50))
        self.Regionefvg.setObjectName("Regionefvg")
        self.etrs89_db = QtWidgets.QCheckBox(self.Regionefvg)
        self.etrs89_db.setGeometry(QtCore.QRect(10, 16, 85, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.etrs89_db.sizePolicy().hasHeightForWidth())
        self.etrs89_db.setSizePolicy(sizePolicy)
        self.etrs89_db.setObjectName("etrs89_db")
        self.horizontalLayout_5.addWidget(self.Regionefvg)
        self.gridLayout_11.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(80, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem1, 2, 0, 1, 1)
        self.cxfspatialite = QtWidgets.QPushButton(self.cxf_load_spatialite)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cxfspatialite.setFont(font)
        self.cxfspatialite.setObjectName("cxfspatialite")
        self.gridLayout_11.addWidget(self.cxfspatialite, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.cxf_load_spatialite)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 3, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_14 = QtWidgets.QLabel(self.cxf_load_spatialite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(70, 0))
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 0, 1, 1)
        self.user = QtWidgets.QLineEdit(self.cxf_load_spatialite)
        self.user.setObjectName("user")
        self.gridLayout_7.addWidget(self.user, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.cxf_load_spatialite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(70, 0))
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 1, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.cxf_load_spatialite)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout_7.addWidget(self.password, 1, 1, 1, 1)
        self.rstpwd = QtWidgets.QPushButton(self.cxf_load_spatialite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rstpwd.sizePolicy().hasHeightForWidth())
        self.rstpwd.setSizePolicy(sizePolicy)
        self.rstpwd.setMinimumSize(QtCore.QSize(0, 0))
        self.rstpwd.setMaximumSize(QtCore.QSize(16777215, 16))
        self.rstpwd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rstpwd.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rstpwd.setFlat(True)
        self.rstpwd.setObjectName("rstpwd")
        self.gridLayout_7.addWidget(self.rstpwd, 2, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_7, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(80, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem2, 5, 0, 1, 1)
        self.geoconn = QtWidgets.QPushButton(self.cxf_load_spatialite)
        self.geoconn.setObjectName("geoconn")
        self.gridLayout_11.addWidget(self.geoconn, 6, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem3, 9, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.cxf_load_spatialite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.registrazione = QtWidgets.QPushButton(self.cxf_load_spatialite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.registrazione.sizePolicy().hasHeightForWidth())
        self.registrazione.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.registrazione.setFont(font)
        self.registrazione.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registrazione.setCheckable(False)
        self.registrazione.setFlat(False)
        self.registrazione.setObjectName("registrazione")
        self.horizontalLayout_3.addWidget(self.registrazione)
        self.gridLayout_11.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.changetrasf = QtWidgets.QFrame(self.cxf_load_spatialite)
        self.changetrasf.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changetrasf.sizePolicy().hasHeightForWidth())
        self.changetrasf.setSizePolicy(sizePolicy)
        self.changetrasf.setMinimumSize(QtCore.QSize(0, 350))
        self.changetrasf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.changetrasf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.changetrasf.setObjectName("changetrasf")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.changetrasf)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.listfogli = QtWidgets.QTreeWidget(self.changetrasf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listfogli.sizePolicy().hasHeightForWidth())
        self.listfogli.setSizePolicy(sizePolicy)
        self.listfogli.setMinimumSize(QtCore.QSize(0, 20))
        self.listfogli.setMaximumSize(QtCore.QSize(16777215, 80))
        self.listfogli.setObjectName("listfogli")
        self.listfogli.headerItem().setText(0, "1")
        self.listfogli.header().setVisible(False)
        self.gridLayout_12.addWidget(self.listfogli, 2, 0, 1, 1)
        self.workdir = QtWidgets.QPushButton(self.changetrasf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workdir.sizePolicy().hasHeightForWidth())
        self.workdir.setSizePolicy(sizePolicy)
        self.workdir.setObjectName("workdir")
        self.gridLayout_12.addWidget(self.workdir, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem4, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.changetrasf)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.traslx = QtWidgets.QLineEdit(self.frame)
        self.traslx.setGeometry(QtCore.QRect(80, 10, 71, 20))
        self.traslx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.traslx.setObjectName("traslx")
        self.trasly = QtWidgets.QLineEdit(self.frame)
        self.trasly.setGeometry(QtCore.QRect(170, 10, 71, 20))
        self.trasly.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trasly.setObjectName("trasly")
        self.orig = QtWidgets.QLineEdit(self.frame)
        self.orig.setGeometry(QtCore.QRect(110, 40, 151, 20))
        self.orig.setMaxLength(32767)
        self.orig.setObjectName("orig")
        self.rotang = QtWidgets.QLineEdit(self.frame)
        self.rotang.setGeometry(QtCore.QRect(110, 70, 41, 20))
        self.rotang.setObjectName("rotang")
        self.scalex = QtWidgets.QLineEdit(self.frame)
        self.scalex.setGeometry(QtCore.QRect(110, 100, 41, 20))
        self.scalex.setObjectName("scalex")
        self.scaley = QtWidgets.QLineEdit(self.frame)
        self.scaley.setGeometry(QtCore.QRect(180, 100, 41, 20))
        self.scaley.setObjectName("scaley")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(160, 10, 16, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(170, 100, 16, 16))
        self.label_25.setObjectName("label_25")
        self.applytrasf = QtWidgets.QPushButton(self.frame)
        self.applytrasf.setGeometry(QtCore.QRect(120, 140, 141, 23))
        self.applytrasf.setObjectName("applytrasf")
        self.getpoint = QtWidgets.QPushButton(self.frame)
        self.getpoint.setGeometry(QtCore.QRect(240, 10, 21, 23))
        self.getpoint.setObjectName("getpoint")
        self.applytrasfall = QtWidgets.QPushButton(self.frame)
        self.applytrasfall.setEnabled(True)
        self.applytrasfall.setGeometry(QtCore.QRect(120, 170, 141, 21))
        self.applytrasfall.setObjectName("applytrasfall")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(20, 150, 91, 31))
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(9, 129, 251, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.traslx.raise_()
        self.trasly.raise_()
        self.orig.raise_()
        self.rotang.raise_()
        self.scalex.raise_()
        self.scaley.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.applytrasf.raise_()
        self.getpoint.raise_()
        self.applytrasfall.raise_()
        self.label_26.raise_()
        self.gridLayout_12.addWidget(self.frame, 3, 0, 1, 1)
        self.gridLayout_11.addWidget(self.changetrasf, 8, 0, 1, 1)
        self.cxfspatialite.raise_()
        self.label_13.raise_()
        self.geoconn.raise_()
        self.changetrasf.raise_()
        self.toolBox.addItem(self.cxf_load_spatialite, "")
        self.Manutenzione = QtWidgets.QWidget()
        self.Manutenzione.setGeometry(QtCore.QRect(0, 0, 302, 661))
        self.Manutenzione.setObjectName("Manutenzione")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.Manutenzione)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Manutenzione)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 180))
        self.groupBox_2.setObjectName("groupBox_2")
        self.server = QtWidgets.QLineEdit(self.groupBox_2)
        self.server.setGeometry(QtCore.QRect(100, 20, 181, 20))
        self.server.setObjectName("server")
        self.database = QtWidgets.QLineEdit(self.groupBox_2)
        self.database.setGeometry(QtCore.QRect(100, 50, 181, 20))
        self.database.setObjectName("database")
        self.user_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.user_2.setGeometry(QtCore.QRect(100, 80, 181, 20))
        self.user_2.setObjectName("user_2")
        self.passwd = QtWidgets.QLineEdit(self.groupBox_2)
        self.passwd.setGeometry(QtCore.QRect(100, 110, 181, 20))
        self.passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwd.setObjectName("passwd")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 46, 13))
        self.label_11.setObjectName("label_11")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(20, 50, 46, 13))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(20, 80, 46, 13))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(20, 110, 46, 13))
        self.label_19.setTextFormat(QtCore.Qt.PlainText)
        self.label_19.setObjectName("label_19")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 140, 252, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.test = QtWidgets.QPushButton(self.layoutWidget)
        self.test.setObjectName("test")
        self.horizontalLayout_4.addWidget(self.test)
        self.paramdb = QtWidgets.QPushButton(self.layoutWidget)
        self.paramdb.setObjectName("paramdb")
        self.horizontalLayout_4.addWidget(self.paramdb)
        self.postgis = QtWidgets.QCheckBox(self.layoutWidget)
        self.postgis.setObjectName("postgis")
        self.horizontalLayout_4.addWidget(self.postgis)
        self.gridLayout_9.addWidget(self.groupBox_2, 9, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.Manutenzione)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setMouseTracking(False)
        self.label_8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Manutenzione)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.del_cat_fg = QtWidgets.QComboBox(self.Manutenzione)
        self.del_cat_fg.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_cat_fg.sizePolicy().hasHeightForWidth())
        self.del_cat_fg.setSizePolicy(sizePolicy)
        self.del_cat_fg.setMinimumSize(QtCore.QSize(0, 20))
        self.del_cat_fg.setMaximumSize(QtCore.QSize(16777215, 20))
        self.del_cat_fg.setEditable(False)
        self.del_cat_fg.setMaxVisibleItems(2147483647)
        self.del_cat_fg.setObjectName("del_cat_fg")
        self.gridLayout.addWidget(self.del_cat_fg, 2, 1, 1, 1)
        self.del_cat_com = QtWidgets.QComboBox(self.Manutenzione)
        self.del_cat_com.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_cat_com.sizePolicy().hasHeightForWidth())
        self.del_cat_com.setSizePolicy(sizePolicy)
        self.del_cat_com.setMinimumSize(QtCore.QSize(0, 20))
        self.del_cat_com.setMaximumSize(QtCore.QSize(16777215, 20))
        self.del_cat_com.setEditable(False)
        self.del_cat_com.setObjectName("del_cat_com")
        self.gridLayout.addWidget(self.del_cat_com, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout, 4, 0, 1, 2)
        self.dbdeletefg = QtWidgets.QPushButton(self.Manutenzione)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbdeletefg.sizePolicy().hasHeightForWidth())
        self.dbdeletefg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dbdeletefg.setFont(font)
        self.dbdeletefg.setCheckable(False)
        self.dbdeletefg.setAutoExclusive(False)
        self.dbdeletefg.setFlat(False)
        self.dbdeletefg.setObjectName("dbdeletefg")
        self.gridLayout_9.addWidget(self.dbdeletefg, 5, 0, 1, 2)
        self.dbdeletecom = QtWidgets.QPushButton(self.Manutenzione)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dbdeletecom.setFont(font)
        self.dbdeletecom.setObjectName("dbdeletecom")
        self.gridLayout_9.addWidget(self.dbdeletecom, 6, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.Manutenzione)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_9.addWidget(self.line_2, 7, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem5, 8, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem6, 1, 1, 1, 1)
        self.dbreset = QtWidgets.QPushButton(self.Manutenzione)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbreset.sizePolicy().hasHeightForWidth())
        self.dbreset.setSizePolicy(sizePolicy)
        self.dbreset.setMinimumSize(QtCore.QSize(0, 24))
        self.dbreset.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dbreset.setFont(font)
        self.dbreset.setCheckable(False)
        self.dbreset.setAutoExclusive(False)
        self.dbreset.setFlat(False)
        self.dbreset.setObjectName("dbreset")
        self.gridLayout_9.addWidget(self.dbreset, 0, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.Manutenzione)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_9.addWidget(self.line, 2, 0, 2, 2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem7, 3, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem8, 10, 0, 1, 1)
        self.toolBox.addItem(self.Manutenzione, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setGeometry(QtCore.QRect(0, 0, 302, 661))
        self.Settings.setObjectName("Settings")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Settings)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.Settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_12 = QtWidgets.QLabel(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.attstile = QtWidgets.QLabel(self.Settings)
        self.attstile.setText("")
        self.attstile.setObjectName("attstile")
        self.horizontalLayout.addWidget(self.attstile)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem10 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem10)
        self.lststile = QtWidgets.QTreeWidget(self.Settings)
        self.lststile.setRootIsDecorated(True)
        self.lststile.setObjectName("lststile")
        self.lststile.headerItem().setText(0, "1")
        self.lststile.header().setVisible(False)
        self.verticalLayout_4.addWidget(self.lststile)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newstile = QtWidgets.QPushButton(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newstile.sizePolicy().hasHeightForWidth())
        self.newstile.setSizePolicy(sizePolicy)
        self.newstile.setMinimumSize(QtCore.QSize(40, 0))
        self.newstile.setMaximumSize(QtCore.QSize(60, 16777215))
        self.newstile.setObjectName("newstile")
        self.horizontalLayout_2.addWidget(self.newstile)
        self.editstile = QtWidgets.QPushButton(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editstile.sizePolicy().hasHeightForWidth())
        self.editstile.setSizePolicy(sizePolicy)
        self.editstile.setMinimumSize(QtCore.QSize(40, 0))
        self.editstile.setMaximumSize(QtCore.QSize(60, 16777215))
        self.editstile.setObjectName("editstile")
        self.horizontalLayout_2.addWidget(self.editstile)
        self.selstile = QtWidgets.QPushButton(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selstile.sizePolicy().hasHeightForWidth())
        self.selstile.setSizePolicy(sizePolicy)
        self.selstile.setMinimumSize(QtCore.QSize(55, 0))
        self.selstile.setMaximumSize(QtCore.QSize(60, 16777215))
        self.selstile.setObjectName("selstile")
        self.horizontalLayout_2.addWidget(self.selstile)
        self.delstile = QtWidgets.QPushButton(self.Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delstile.sizePolicy().hasHeightForWidth())
        self.delstile.setSizePolicy(sizePolicy)
        self.delstile.setMinimumSize(QtCore.QSize(50, 0))
        self.delstile.setMaximumSize(QtCore.QSize(60, 16777215))
        self.delstile.setObjectName("delstile")
        self.horizontalLayout_2.addWidget(self.delstile)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.toolBox.addItem(self.Settings, "")
        self.Informazioni = QtWidgets.QWidget()
        self.Informazioni.setGeometry(QtCore.QRect(0, 0, 302, 661))
        self.Informazioni.setObjectName("Informazioni")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Informazioni)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gisplan = QtWidgets.QPushButton(self.Informazioni)
        self.gisplan.setMinimumSize(QtCore.QSize(0, 0))
        self.gisplan.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/Cxf_in/logonewsmall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gisplan.setIcon(icon)
        self.gisplan.setIconSize(QtCore.QSize(200, 50))
        self.gisplan.setFlat(False)
        self.gisplan.setObjectName("gisplan")
        self.gridLayout_8.addWidget(self.gisplan, 0, 0, 1, 3)
        spacerItem13 = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem13, 2, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(23, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem14, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.Informazioni)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 4, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.Informazioni)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(270, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setLineWidth(1)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 5, 0, 1, 3)
        spacerItem15 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem15, 6, 1, 1, 1)
        self.donate = QtWidgets.QPushButton(self.Informazioni)
        self.donate.setMinimumSize(QtCore.QSize(220, 0))
        self.donate.setMaximumSize(QtCore.QSize(300, 16777215))
        self.donate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.donate.setAutoFillBackground(False)
        self.donate.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/Cxf_in/supporto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.donate.setIcon(icon1)
        self.donate.setIconSize(QtCore.QSize(240, 40))
        self.donate.setAutoDefault(False)
        self.donate.setFlat(True)
        self.donate.setObjectName("donate")
        self.gridLayout_8.addWidget(self.donate, 2, 1, 1, 1)
        self.toolBox.addItem(self.Informazioni, "")
        self.gridLayout_4.addWidget(self.toolBox, 1, 0, 1, 1)
        cercacat.setWidget(self.dockWidgetContents)

        self.retranslateUi(cercacat)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(cercacat)

    def retranslateUi(self, cercacat):
        _translate = QtCore.QCoreApplication.translate
        cercacat.setWindowTitle(_translate("cercacat", "CXF IN"))
        self.viewall.setText(_translate("cercacat", "Visualizza tutto"))
        self.viewsel.setText(_translate("cercacat", "Visualizza Selezione"))
        self.singolfg.setText(_translate("cercacat", "mappa continua"))
        self.label_9.setText(_translate("cercacat", "Comune"))
        self.label_10.setText(_translate("cercacat", "|-----Foglio_All_Sez"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.viewspatialite), _translate("cercacat", "Visualizzazione Fogli SpatiaLite"))
        self.label_4.setText(_translate("cercacat", "Foglio"))
        self.label_5.setText(_translate("cercacat", "Mappale"))
        self.label.setText(_translate("cercacat", "Comune"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ric_mapp), _translate("cercacat", "Ricerca Mappale"))
        self.cxfmemory.setText(_translate("cercacat", "Importa files CXF to Memory"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.cxf_load_memory), _translate("cercacat", "Carica CXF in Memory Layer"))
        self.georef_db.setText(_translate("cercacat", "Georeferenziato"))
        self.Regionefvg.setTitle(_translate("cercacat", "Solo per Regione F.V.G. "))
        self.etrs89_db.setText(_translate("cercacat", "Grigliati "))
        self.cxfspatialite.setText(_translate("cercacat", "Importa files CXF nel DB SpatiaLite"))
        self.label_13.setText(_translate("cercacat", "Registrazione utente per georeferenziazione"))
        self.label_14.setText(_translate("cercacat", " UTENTE        :"))
        self.label_15.setText(_translate("cercacat", " PASSWORD  :"))
        self.rstpwd.setText(_translate("cercacat", "Password dimenticata??"))
        self.geoconn.setText(_translate("cercacat", "Connessione al server di georeferenziazione"))
        self.label_16.setText(_translate("cercacat", "Non hai un account su PrgCloud :"))
        self.registrazione.setText(_translate("cercacat", "Registrati !!"))
        self.listfogli.setSortingEnabled(True)
        self.workdir.setText(_translate("cercacat", "Directory dei fogli"))
        self.label_20.setText(_translate("cercacat", "Traslazione   X"))
        self.label_21.setText(_translate("cercacat", "Y"))
        self.label_22.setText(_translate("cercacat", "Origine"))
        self.label_23.setText(_translate("cercacat", "Angolo rotazione"))
        self.label_24.setText(_translate("cercacat", "Scalatura   X"))
        self.label_25.setText(_translate("cercacat", "Y"))
        self.applytrasf.setText(_translate("cercacat", "Singolo foglio"))
        self.getpoint.setText(_translate("cercacat", "..."))
        self.applytrasfall.setText(_translate("cercacat", " Tutti i fogli della directory"))
        self.label_26.setText(_translate("cercacat", "Applica parametri correttivi"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.cxf_load_spatialite), _translate("cercacat", "Carica CXF su DB Spaziale"))
        self.groupBox_2.setTitle(_translate("cercacat", "Database account"))
        self.label_11.setText(_translate("cercacat", "Server"))
        self.label_17.setText(_translate("cercacat", "Database"))
        self.label_18.setText(_translate("cercacat", "User"))
        self.label_19.setText(_translate("cercacat", "Password"))
        self.test.setText(_translate("cercacat", "Test database"))
        self.paramdb.setText(_translate("cercacat", "Salva parametri"))
        self.postgis.setText(_translate("cercacat", "Usa Postgis"))
        self.label_8.setText(_translate("cercacat", "Foglio"))
        self.label_3.setText(_translate("cercacat", "Comune"))
        self.dbdeletefg.setText(_translate("cercacat", "Cancella Foglio Selezionato"))
        self.dbdeletecom.setText(_translate("cercacat", "Cancella Comune Selezionato"))
        self.dbreset.setText(_translate("cercacat", "Svuota intero DB SpatiaLite"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Manutenzione), _translate("cercacat", "Manutenzione Database Catasto "))
        self.label_2.setText(_translate("cercacat", "Rappresentazione Grafica"))
        self.label_12.setText(_translate("cercacat", "Grafica attuale:   "))
        self.newstile.setText(_translate("cercacat", "Crea"))
        self.editstile.setText(_translate("cercacat", "Edita"))
        self.selstile.setText(_translate("cercacat", "Seleziona"))
        self.delstile.setText(_translate("cercacat", "Cancella"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Settings), _translate("cercacat", "Impostazioni"))
        self.label_7.setText(_translate("cercacat", "<html><head/><body><p align=\"justify\">La presente versione permette di georiferire tutti i fogli catastali CXF dell\'ITALIA. </p><p align=\"justify\">Per fare ciò bisogna registrarsi nel menu Carica CXF SpatiaLite. </p><p align=\"justify\">Tale georiferimento può essere facilmente migliorato attraverso un\'altro plugin.</p><p align=\"justify\">Parametri di correzioe per singolo fogli. </p><p align=\"justify\">(Per informazioni non esitate a contattarmi)</p><p align=\"justify\"><br/>A seguito della connessione verrà attivato il bottone di spunta per la georeferenziazione </p><p align=\"justify\">PRIMA DI INIZIARE: </p><p align=\"justify\">Su menu Manutenzione Catasto SpatiaLite utilizzare la funzione Svuota intero DB SpatiaLite </p><p align=\"justify\">Questa operazione permette di impostare il sistema di riferimento cartografico di arrivo.</p></body></html>"))
        self.label_6.setText(_translate("cercacat", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,sans-serif\'; font-size:12pt;\">Autore:     </span>Fabio Saccon (Paolo)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Codroipo (UD) </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Email :    saccon@gisplan.it</p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Informazioni), _translate("cercacat", "INFORMAZIONI"))

from . import resources_rc
